language: cpp
compiler:
    - gcc
before_install:
    - curl http://download.opensuse.org/repositories/YaST:/Head:/Travis/xUbuntu_12.04/Release.key | sudo apt-key add -
    - echo "deb http://download.opensuse.org/repositories/YaST:/Head:/Travis/xUbuntu_12.04/ ./" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -q
    - sudo apt-get install --no-install-recommends -y docbook-xsl xsltproc yast2-core-dev yast2-devtools libyui-dev
script:
    - make -f Makefile.cvs
    - make -j 4
    - make check
    - sudo make install

